config/routes.rb
Clgn2::Application.routes.draw do
  scope '(:locale)', :locale => /en|tr/  do
    root :to => "sn_urls#new"
    resource :home_page
    resources :sn_urls
    get 'sn_url_search' => 'sn_urls#search', :as => 'sn_url_search'
    post 'sn_url_go' => 'sn_urls#go', :as => 'sn_url_go'

    resources :users
    devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }, :skip => [:registrations]
    devise_scope :users do

    end
  end
end

app/models/sn_url.rb
class SnUrl < ActiveRecord::Base
  attr_accessible :sn_code_id, :value

  belongs_to :sn_code
end

app/controllers/sn_urls_controller.rb
class SnUrlsController < ApplicationController

  def index
    @table_id = "sn_urls"
    @sn_urls = SnUrl.page(params[:page]).order("id ASC")
    respond_to do |format|
      format.html
      format.json { render json: @sn_urls }
    end
  end

  def show
    @sn_url = SnUrl.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @sn_url }
    end
  end

  def new
    @sn_url = SnUrl.new
    respond_to do |format|
      format.html
      format.json { render json: @sn_url }
    end
  end

  def edit
    @sn_url = SnUrl.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @sn_url }
    end
  end

  def create
    @sn_url = SnUrl.new(params[:sn_url])
    sn_code_check = createSnCode(@sn_url, params[:number_of_digits].to_i, params[:short_name])
    respond_to do |format|
      if sn_code_check == 0 and @sn_url.save
        format.html { redirect_to @sn_url }
        format.json { render json: @sn_url, status: :created }
      else
        if sn_code_check == -1
          flash[:error] = (t "errors.short_name_exists")
        elsif sn_code_check == -2
          flash[:error] = (t "errors.full_number_of_digits")
        end
        puts "error on creating SnUrl"
        puts @sn_url.errors.count
        format.html { render action: "new" }
        format.json { render json: @sn_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @sn_url = SnUrl.find(params[:id])
    respond_to do |format|
      if @sn_url.update_attributes(params[:sn_url])
        format.html { redirect_to @sn_url }
        format.json { head :no_content }
      else
        puts "error on updating SnUrl"
        format.html { render action: "edit" }
        format.json { render json: @sn_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sn_url = SnUrl.find(params[:id])
    if @sn_url.destroy
      respond_to do |format|
        format.html { redirect_to sn_urls_path}
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        puts "error on destroying SnUrl"
        format.html { redirect_to sn_url_path, alert: @sn_url.errors.full_messages.to_sentence }
        format.json { head :no_content }
      end
    end
  end

  def search
  end

  def go
    sn_code = SnCode.find_by_value(params[:q])
    if sn_code
      @sn_url = SnUrl.find_all_by_sn_code_id(sn_code.id).first
    else
      sn_code = SnCode.find_by_short_name(params[:q])
        if sn_code
          @sn_url = SnUrl.find_all_by_sn_code_id(sn_code.id).first
        else
          puts "no SN URL found for SN Code #{params[:q]}"
          flash[:error] = (t "errors.no_sn_url_found")
        end
    end
    respond_to do |format|
      if sn_code
        format.html
        format.json { render json: @sn_url }
      else
        format.html { redirect_to sn_url_search_path}
        format.json {head :no_content}
      end
    end
  end

end

app/helpers/sn_urls_helper.rb
module SnUrlsHelper
end

app/views/sn_urls/_form.html.erb
<% if @sn_url.errors.any? or flash[:error] %>
  <div class="alert-message error">
    <p>
      <strong>
          <% if @sn_url.errors.any? %>
            <%= t "errors.save_error", :count => @sn_url.errors.count, :save_obj => (t "sn_url") %>
            <br />
            <% @sn_url.errors.full_messages.each do |msg| %>
                <strong>- <%= msg %></strong><br/>
            <% end %>
          <% elsif flash[:error] %>
            <%= (t "errors.save_error") %> <%= flash[:error] %>
          <% end %>
      </strong>
    </p>
  </div>
<% end %>

<%= simple_form_for @sn_url do |f| %>
  <div class="inner_wrap">
    <div class="form field_list">
      <div class='field odd'>
        <%= label_tag :number_of_digits_label, (t "list_attributes.number_of_digits"), :class =>  "form_label" %>
        <%= select_tag :number_of_digits, "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option>".html_safe, { :class => "form_input"} %>
      </div>
		  <div class='field'>
		    <%= f.input :value, :label=> (t "list_attributes.url"), :label_html => {:class => "form_label"} %>
		  </div>
      <% if current_user %>
        <div class='field odd'>
          <%= label_tag :short_name_label, (t "list_attributes.short_name"), :class =>  "form_label" %>
          <%= text_field_tag :short_name %>
        </div>
      <% end %>
		  <div class="submit">
	      <%= f.button :submit, I18n.t("actions.save"), :id => "fs" %>
	    </div>
	  </div>
  </div>
<% end %>

app/views/sn_urls/_sn_url.html.erb
<tr>
    <td><%= sn_url.id %></td>
    <td><%= sn_url.sn_code.value %></td>
    <td><%= sn_url.value %></td>
    <td><%= sn_url.sn_code.number_of_digits %></td>
    <% if current_user %>
    	<td><%= sn_url.sn_code.number_of_digits %></td>
    <% else %>
    	<td>N/A</td>
    <% end %>

    <td class="act">
        <%= link_to (t "actions.show"), sn_url %>
        <%= link_to (t "actions.edit"), edit_sn_url_path(sn_url) %>
        <%= link_to (t "actions.destroy"), sn_url, method: :delete, data: { confirm: I18n.t("actions.confirm_to") } %></td>
    </td>
</tr>

app/views/sn_urls/edit.html.erb
<h2 class="page_name"><%= (t "edit_sn_url")%></h2>
<%= render 'form' %>

app/views/sn_urls/go.html.erb
<% if flash[:error] %>
  <div class="alert-message error">
    <p>
      <strong>
        <%= (t "errors.save_error") %> <%= flash[:error] %>
      </strong>
    </p>
  </div>

<% else %>
	<a id="hidden_link" onClick="go_to_url('<%= @sn_url.value %>')" href="#"></a>

	<script>
		$(document).ready(function(){$("#hidden_link")[0].onclick.apply($("#hidden_link")[0]);});
		
		function go_to_url(url)
		{
			window.location.href = "http://" + url;
		}
	</script>

<% end %>

app/views/sn_urls/index.html.erb
<h2 class="page_name"><%= (t "show_sn_urls")%></h2>
	
  <%= paginated_collection_content(@sn_urls, @table_id, [(t "list_attributes.id"), (t "list_attributes.sn_code"), (t "list_attributes.url"), (t "list_attributes.number_of_digits"), (t "list_attributes.short_name")]) %>
  <%= paginate_footer(@sn_urls) %>

app/views/sn_urls/new.html.erb
<h2 class="page_name"><%= (t "new_sn_url")%></h2>
<%= render 'form' %>

app/views/sn_urls/search.html.erb
<% if flash[:error] %>
  <div class="alert-message error">
    <p>
      <strong>
        <%= (t "errors.save_error") %> <%= flash[:error] %>
      </strong>
    </p>
  </div>
<% end %>

<h2 class="page_name"><%= (t "search_sn_url")%></h2>

<%= form_tag(sn_url_go_path) do %>
	<div class="inner_wrap">
	<div class="form field_list">
		  <div class='field'>
		  	<%= label_tag :q, (t "list_attributes.sn_code"), :class =>  "form_label" %>
		    <%= text_field_tag :q %>
		  </div>
		  <div class="submit">
	      <%= submit_tag I18n.t("actions.search"), :id => "fs" %>
	    </div>
	  </div>
	</div>
<% end %>

app/views/sn_urls/show.html.erb
<h2 class="page_name"><%= (t "show_sn_url")%></h2>
<div class="inner_wrap">
  <div class="field_list">
    <div class="field">
      <label class="show_label"><%= (t "list_attributes.id") %></label>
      <span><%= @sn_url.id %></span>
    </div>
    <div class="field odd">
      <label class="show_label"><%= (t "list_attributes.url") %></label>
      <a href="<%= @sn_url.value %>"><%= @sn_url.value %></a>
    </div>
    <div class="field">
      <label class="show_label"><%= (t "list_attributes.sn_code") %></label>
      <span><%= @sn_url.sn_code.value %></span>
    </div>
    <div class="field">
      <label class="show_label"><%= (t "list_attributes.number_of_digits") %></label>
      <span><%= @sn_url.sn_code.number_of_digits %></span>
    </div>
    <% unless @sn_url.sn_code.short_name.nil? %>
      <div class="field">
        <label class="show_label"><%= (t "list_attributes.short_name") %></label>
        <span><%= @sn_url.sn_code.short_name %></span>
      </div>
    <% end %>
  </div>
</div>